apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigc-gateway
  labels:
    app: aigc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigc-gateway
  template:
    metadata:
      labels:
        app: aigc-gateway
    spec:
      containers:
        - name: aigc-gateway
          image: registry.cn-beijing.aliyuncs.com/acs/aigc-gateway:v0.1.0 # replace it with your exactly <image_name:tags>
          command:
            - "./aigc-gateway"
          env:
            - name: App_Id
              value: "550tqtqmoxfgc2efcs0hg"
            - name: App_Secret
              value: "os1dow3fzqrukv8ngvoat"
            - name: M2M_Id
              value: ""
            - name: M2M_Secret
              value: ""
            - name: Basic_Auth_Token
              value: "eHp3ZnB3cjR3cGhhdmVrcDY4ZGVnOjJjazF3YnY5cWdvbmw1ZjZtNWdjdw=="
            - name: Redirect_Url
              value: "https://dashboard.c5464a5f2c39341d3b3eda6e2dd37b55.cn-hangzhou.alicontainer.com/"
            - name: Endpoint
              value: "https://logto.c5464a5f2c39341d3b3eda6e2dd37b55.cn-hangzhou.alicontainer.com/"
          ports:
            - containerPort: 8090
              name: dashboard
      serviceAccountName: aigc-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: aigc-gateway
  labels:
    app: aigc-gateway
spec:
  selector:
    app: aigc-gateway
  ports:
    - protocol: TCP
      name: dashboard
      port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aigc-gateway
  annotations:
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "dashboard.c5464a5f2c39341d3b3eda6e2dd37b55.cn-hangzhou.alicontainer.com"
      secretName: tls-logto
  rules:
    - host: "dashboard.c5464a5f2c39341d3b3eda6e2dd37b55.cn-hangzhou.alicontainer.com"
      http:
        paths:
          - backend:
              service:
                name: aigc-gateway
                port:
                  number: 8090
            pathType: ImplementationSpecific
            path: "/"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aigc-gateway
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aigc-gateway
rules:
- apiGroups:
    - game.kruise.io
  resources:
    - gameservers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - game.kruise.io
  resources:
    - gameservers/finalizers
  verbs:
    - update
- apiGroups:
    - game.kruise.io
  resources:
    - gameservers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - game.kruise.io
  resources:
    - gameserversets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - game.kruise.io
  resources:
    - gameserversets/finalizers
  verbs:
    - update
- apiGroups:
    - game.kruise.io
  resources:
    - gameserversets/status
  verbs:
    - get
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aigc-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aigc-gateway
subjects:
  - kind: ServiceAccount
    name: aigc-gateway
    namespace: default